version: '3.4'
services:
  db:
    hostname: mysql
    image: mysql:8.0.25
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
volumes:
  db_data: